### ISSUE TITLE
Studio: Limit box-sizing

### ISSUE THREAD

**Issue by compulim** [Microsoft/BotFramework-Emulator#391]
In `resizer.css`:

```css
*, *:before, *:after {
    -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
}
```

Can we limit this style to only elements that need this and not global or any descendants?
